### PR TITLE
[WIP] Add pricing streaming

### PR DESCRIPTION
**Pull request by joseluis-fw**
Example to use:

```ruby
require 'oanda_api_v20'

access_token = 'XXXXX-YYYYY'
client = OandaApiV20.new(access_token: access_token, practice: true, stream: true, debug: false)

account_id = 'XXX-YYY-ZZZ'

options = {
  'instruments' => 'EUR_USD,USD_CAD'
}

client.account(account_id).pricing_stream(options).show do |fragment|
  puts JSON.pretty_generate(fragment)
end
```

### CODE REVIEW

**Comment by joseluis-fw** [comment]
@kobusjoubert What do you think to integrate the feature in the client?

I can try to write some tests, but as it's streaming it can be tricky.

**Comment by joseluis-fw** [comment]
@kobusjoubert What do you think to integrate the feature in the client?

I can try to write some tests, but as it's streaming it can be tricky.

**Comment by josacar** [comment]
@kobusjoubert What do you think to integrate the feature in the client?

I can try to write some tests, but as it's streaming it can be tricky.

**Comment by josacar** [comment]
Output example:

```
$ curl -i -H "Authorization: Bearer xxxxx-xxxxx"   "https://stream-fxpractice.oanda.com/v3/accounts/101-004-8153273-001/pricing/stream?instruments=EUR_USD&20CAD_USD"
HTTP/1.1 200 OK
Server: openresty/1.9.15.1
Date: Fri, 06 Apr 2018 08:23:06 GMT
Content-Type: application/octet-stream
Transfer-Encoding: chunked
Connection: close
Access-Control-Allow-Headers: Authorization, Content-Type, Accept-Datetime-Format, OANDA-Agent, ETag
Access-Control-Allow-Methods: PUT, PATCH, POST, GET, OPTIONS, DELETE
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag
RequestID: 762992674915002302

{"type":"PRICE","time":"2018-04-06T08:23:03.676250377Z","bids":[{"price":"1.22220","liquidity":10000000}],"asks":[{"price":"1.22232","liquidity":10000000}],"closeoutBid":"1.22205","closeoutAsk":"1.22247","status":"tradeable","tradeable":true,"instrument":"EUR_USD"}
{"type":"PRICE","time":"2018-04-06T08:23:06.629285563Z","bids":[{"price":"1.22229","liquidity":10000000}],"asks":[{"price":"1.22242","liquidity":10000000}],"closeoutBid":"1.22214","closeoutAsk":"1.22257","status":"tradeable","tradeable":true,"instrument":"EUR_USD"}
{"type":"PRICE","time":"2018-04-06T08:23:07.459292352Z","bids":[{"price":"1.22234","liquidity":10000000}],"asks":[{"price":"1.22246","liquidity":10000000}],"closeoutBid":"1.22219","closeoutAsk":"1.22261","status":"tradeable","tradeable":true,"instrument":"EUR_USD"}
{"type":"HEARTBEAT","time":"2018-04-06T08:23:11.199115245Z"}
{"type":"PRICE","time":"2018-04-06T08:23:11.577334997Z","bids":[{"price":"1.22238","liquidity":10000000}],"asks":[{"price":"1.22251","liquidity":10000000}],"closeoutBid":"1.22223","closeoutAsk":"1.22266","status":"tradeable","tradeable":true,"instrument":"EUR_USD"}
{"type":"HEARTBEAT","time":"2018-04-06T08:23:16.205159607Z"}
{"type":"HEARTBEAT","time":"2018-04-06T08:23:21.208791300Z"}
{"type":"HEARTBEAT","time":"2018-04-06T08:23:26.218236292Z"}
{"type":"HEARTBEAT","time":"2018-04-06T08:23:31.224428497Z"}
{"type":"PRICE","time":"2018-04-06T08:23:33.061020186Z","bids":[{"price":"1.22236","liquidity":10000000}],"asks":[{"price":"1.22248","liquidity":10000000}],"closeoutBid":"1.22221","closeoutAsk":"1.22263","status":"tradeable","tradeable":true,"instrument":"EUR_USD"}
{"type":"PRICE","time":"2018-04-06T08:23:35.760667990Z","bids":[{"price":"1.22241","liquidity":10000000}],"asks":[{"price":"1.22253","liquidity":10000000}],"closeoutBid":"1.22226","closeoutAsk":"1.22268","status":"tradeable","tradeable":true,"instrument":"EUR_USD"}
{"type":"HEARTBEAT","time":"2018-04-06T08:23:36.230191329Z"}
{"type":"PRICE","time":"2018-04-06T08:23:37.114414791Z","bids":[{"price":"1.22238","liquidity":10000000}],"asks":[{"price":"1.22250","liquidity":10000000}],"closeoutBid":"1.22223","closeoutAsk":"1.22265","status":"tradeable","tradeable":true,"instrument":"EUR_USD"}
{"type":"PRICE","time":"2018-04-06T08:23:37.475661799Z","bids":[{"price":"1.22238","liquidity":10000000}],"asks":[{"price":"1.22251","liquidity":10000000}],"closeoutBid":"1.22223","closeoutAsk":"1.22266","status":"tradeable","tradeable":true,"instrument":"EUR_USD"}
{"type":"PRICE","time":"2018-04-06T08:23:37.526712582Z","bids":[{"price":"1.22239","liquidity":10000000}],"asks":[{"price":"1.22250","liquidity":10000000}],"closeoutBid":"1.22224","closeoutAsk":"1.22265","status":"tradeable","tradeable":true,"instrument":"EUR_USD"}
```

**Comment by kobusjoubert** [comment]
Hi @josacar , funny I was just looking at the streaming branch earlier today. I really want to get the streaming endpoint merged into master. I made a streaming branch off of your the changes made by you and @peertransfer last year.

https://github.com/kobusjoubert/oanda_api_v20/commit/82f4ffd62b2c3854fd3a65872e7c9750fc238343

I do think we should return all responses including the HEARTBEAT type, and let the user decide what to use and what not to. Your application may need the HEARTBEAT type for network monitoring etc.

I want to get this merged early this year, hopefully this month. I'll see what I can do about tests and then merge it into master.

**Comment by josacar** [comment]
OK, good news then, we can do some PRs to your `streaming` branch then.

I'll close this PR

**Comment by kobusjoubert** [comment]
Thanks @josacar

**Comment by josacar** [comment]
@kobusjoubert We are hitting the same issue as here: https://github.com/nukeproof/oanda_api/issues/18

We are working on a fix and we will start from your `streaming` branch

**Comment by kobusjoubert** [comment]
@josacar thanks for looking into this. I'm also trying to reproduce the issue now. Let me know if there is anything I can help with.

**Pull request closed without merging**
