### PR TITLE
Pricing stream endpoint

### PR DESCRIPTION
**Pull request by joseluis-fw**
Fixes #5

### CODE REVIEW

**Comment by kobusjoubert** [comment]
Hi @joseluis-fw, thank you for your pull request. I'm busy reviewing and will merge today hopefully and release a new version. Thank you so much for your help on this repository, I really appreciate it.

**Comment by josacar** [comment]
@kobusjoubert we are testing it heavily in staging, but we have had no error so far

**Comment by kobusjoubert** [comment]
@joseluis-fw that's great news! I'm also busy testing with these instruments, also don't have any issues yet.

options = {'instruments'=>'AUD_CHF,AUD_JPY,CAD_CHF,CHF_JPY,EUR_AUD,EUR_CHF,EUR_GBP,EUR_JPY,EUR_USD,GBP_AUD,GBP_JPY,GBP_USD,NZD_JPY,NZD_USD,USD_CAD,USD_CHF,AUD_CAD,AUD_CHF,AUD_JPY,AUD_NZD,AUD_USD,CAD_CHF,CAD_JPY,CHF_JPY,EUR_AUD,EUR_CAD,EUR_CHF,EUR_GBP,EUR_JPY,EUR_USD,EUR_NZD,GBP_AUD,GBP_CAD,GBP_CHF,GBP_JPY,GBP_NZD,GBP_USD,NZD_CAD,NZD_CHF,NZD_JPY,NZD_USD,USD_CAD,USD_CHF,USD_JPY,EU50_EUR,FR40_EUR,DE30_EUR,JP225_USD,HK33_HKD,NL25_EUR,US30_USD,SG30_SGD,UK100_GBP,CORN_USD,NATGAS_USD,SOYBN_USD,SUGAR_USD,WHEAT_USD,WTICO_USD,SPX500_USD,US2000_USD,NAS100_USD,TWIX_USD,IN50_USD,CN50_USD'}

**Comment by josacar** [comment]
thank you for being such a good maintainer

**Pull request merged**
